"""Initial migration and seed fisrt user

Revision ID: 1a917a661eb6
Revises: 
Create Date: 2020-09-07 20:58:25.709191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from werkzeug.security import generate_password_hash

revision = "1a917a661eb6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    role = op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password", sa.String(length=120), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###

    # Custom add seed role and first user
    password = generate_password_hash("test1234", method="sha256")
    op.bulk_insert(role, [{"id": 1, "title": "User"}, {"id": 2, "title": "Moderator"}])
    # FIXME: пример execute
    op.execute(
        "INSERT INTO public.user (id, email, password, role_id) "
        f"VALUES (1, 'test@test.test', '{password}', 2);"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("role")
    # ### end Alembic commands ###
